In [1]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


### Python List vs Numpy Array
1. Numpy arrays are faster(optimized in C)
2. Numpy stores data in continuous memory blocks
3. Numpy array uses less memmory(optimized storage)
4. Numpy has built-in mathematical function
5. Numpy array supports direct vectorized operations

In [2]:
# execution performance
size = 1_000_000

#python list
py_list = list(range(size)) 
start_time = time.time()
sq_list = [x**2 for x in py_list]
end_time = time.time()
print(f"python list time = {end_time-start_time} seconds")

#numpy array
np_arr = np.array(py_list)
start_time = time.time()
sq_arr = np_arr**2  #vectorization -> like list we dont have to apply any loop
end_time = time.time()
print(f"numpy array time = {end_time-start_time} seconds")

python list time = 0.07909131050109863 seconds
numpy array time = 0.0035390853881835938 seconds


In [12]:
#memory
import sys

print(f"python list size = {sys.getsizeof(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")


python list size = 8000056 bytes
numpy array size = 8000000 bytes


### why is Numpy faster
1. Homogeneous Data Types and Contiguous Memory
2. Vector Operations & C Implementations
3. Reduced Overhead

### Creating Numpy Array

In [ ]:
#create - from lists

#1d array for 1d list
arr = np.array([1,2,3,4,5])
print(arr,type(arr) , arr.dtype,arr.shape)  # shape = dimension of array - in 1d it is number of element
 
arr2 = np.array([1,2,3,4,5,"yash"])
print(arr2,type(arr2), arr2.dtype, arr2.shape)  # all converted into string because numpy array couldnt have element of different data type like list


#2d array from 2d list
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])  # there should be proper rectangular dimension -> mtlb proper rectangle banna chahiye
print(arr_2d,arr_2d.shape) #shape = dimension(rows x columns) of array that is 4X3 here 



[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'yash'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [41]:
#create - from scratch (using built in functions)
arr1 = np.zeros((2,3),dtype = "int64")  # it creates a array of dimension 2x3 with all values 0 , we pass dimension as a tuple, we can pass datatype as dtype = "int64" 
print(arr1,arr1.shape)

arr2 = np.ones((2,3),dtype = "int64") #prefill with one , if we dont pass dtype by default float here
print(arr2)
arr3 = np.ones((5,)) #  to create 1d array we pass dimension as (x,)
print(arr3)

arr4 = np.full((3,4),100,) # it prefill with the number we pass here it will prefill with 100 has we have passed 100
print(arr4)

arr5 = np.eye(3) # it creates identity matrix here we dont pass dimension we pass single value let say x then it will create identity matrix of (x X x)
print(arr5)

arr6 = np.arange(0,11,2) # it is like range function which have start end and step it creates a 1d array whose value start from start and goes till (end value -1) and step size is 1 by default if we dosent pass
print(arr6)

arr7 = np.linspace(1,100,4) # it creates evenly spaced arrays -> mean let say i want to creat array from 1 to 100 but i want size to be 4 we pass it as (1,100,4),it will creates array of size 4 whose every element is evenly spaced from its neighbour
print(arr7)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]]
[1. 1. 1. 1. 1.]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10]
[  1.  34.  67. 100.]


### Properties of Numpy Arrays

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) # dimension = m x n - (3,3)
print(arr.size) # total elements  - 9
print(arr.dtype) # data type
print(arr.ndim) # no. of dimension means is it 1d or 2d or 3d since it is 2d array it will print 2

float_arr = arr.astype(np.float64) # it is one type of typecasting it changes data type in numpy array    we have already seen dtype if we want to do it from scratch
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


### Operations on Numpy Arrays
1. Reshaping
2. Indexing(1D & 2D array)
3. Fancy & Boolean Indexing
4. Slicing

In [45]:
#Reshape
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape(3,2)
print(reshaped,reshaped.shape)
# reshaping is only possible if we have compatible number of element means after reshaping rectangle banna chahiye means we can reshape 2x3 to 3x3

#flatten
flattened = arr.flatten() #2d->1d
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
#Indexing
#1d
arr = np.array([1,2,3,4,5])

print(arr[0]) #1
print(arr[3]) #4


1
4


In [47]:
#2d [row][column]
arr = np.array([[1,2,3],[4,5,6]])

print(arr[0][2]) #2

3


In [48]:
#Fancy Indexing -> can access particular set of values all together
arr = np.array([1,2,3,4,5])

# let we want to excess index 0,1,3 all together
idx = [0,1,3]
print(arr[idx])


[1 2 4]


In [ ]:
#Boolean Indexing  -> depending upon a particular condition which we will pass all values satisfieng that condition will print
arr = np.array([1,2,3,4,5])
print(arr[arr > 3])  #4,5
print(arr[arr%2==0])  #2,4
print(arr[(arr%2!=0) & (arr>3)]) #5  and mixes two single yes/no answers, & mixes yes/no for each item in a list.thats why we uses & here

[4 5]
[2 4]
[5]


In [ ]:
#Slicing -> in list slicing it creates a copy when we do slcing, but in numpy array when we do slicing copy create nhi hoti ek view hota hai we are viewing the original array itself it is not creating any copy like list do and since it is not creating copy there is no any extra memory is used in numpy array like list
#1d
arr = np.array([1,2,3,4,5])

print(arr[1:4])#[start:end:step]
print(arr[1:4:2])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [62]:
#Copy vs View
print("In List")
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print("sub list obtained by slicing on original list = ",sub_list)
sub_list[0]=200
print("doing change in sub list = ",sub_list)
print("original list doesnt get changed  = ",nums)
print("hence it is ceating a copy")

print("\n\nIn Numpy Array")
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print("sub array obtained by slicing on original array = ",sub_arr)
sub_arr[0]=200
print("doing change in sub array = ",sub_arr)
print("original array also get changed  = ",arr)
print("hence it is not ceating copy only view is created")

In List
sub list obtained by slicing on original list =  [2, 3]
doing change in sub list =  [200, 3]
original list doesnt get changed  =  [1, 2, 3, 4, 5]
hence it is ceating a copy


In Numpy Array
sub array obtained by slicing on original array =  [2 3]
doing change in sub array =  [200   3]
original array also get changed  =  [  1 200   3   4   5]
hence it is not ceating copy only view is created


In [ ]:
# slicing creates view but if we actually want to create copy then we do 
sub_arr = arr[1:3].copy() #  -> it creates copy -> copieng the view of sliced variable 

### Common Data Types
1. Integers: int32,inte64
2. Floating point nums: float32,float64
3. Boolean: bool
4. Complex nums: complex64,complex128
5. String: S(byte-str) & U(unicode-str)
6. Object: generic python objects-object
7. we can downcast the datatype for example by default it is using int 64 but we require only int 8 then we can downcast it by using astype or dtype we have discussed already

In [ ]:
#Data Types

arr = np.array([1,2,3,4,5])
print(arr,arr.dtype)         #int64


[1 2 3 4 5] int64


In [67]:
arr = np.array([1,2,3.14,4,5])
print(arr,arr.dtype)     #float64

[1.   2.   3.14 4.   5.  ] float64


In [ ]:
arr = np.array([1,2,3,4,5,"prime"])
print(arr,arr.dtype)    #U21   # it is not advisable to use numpy array for string and object datatype numpy array is used to work  on numerical data set 

['1' '2' '3' '4' '5' 'prime'] <U21


In [73]:
arr = np.array([1,2-3j,3,4+5j,5])
print(arr,arr.dtype)  #complex128

[1.+0.j 2.-3.j 3.+0.j 4.+5.j 5.+0.j] complex128


In [ ]:
arr = np.array(["prime",{1,2,3},3.14])
print(arr,arr.dtype)  #object -> if heterogenius data type
# it is not advisable to use numpy array for string and object datatype numpy array is used to work on numerical data set 

['prime' {1, 2, 3} 3.14] object


### Axes in Multi-dimensional arrays
1) 1D ---> 1 Axis (axis 0)
2) 2D ---> 2 Axes (axis 0->rows) (axis 1->columns)
3) 3D ---> 3 Axes (axis 0->depth/layers) (axis 1->row in each layer) (axis 2->column)

4) let we have a matrix and we want to perform an operation
5) operation row wise -> axis 1 -> horizontally operation perform karta hai
6) operation column wise -> axis 0 ->vertically operation perform karta hai
7) we can imagine 3d array as a combination of 2d arrays jaise ki we have 3 2d array 2d_1,2d_2,2d_3 then let say 2d_1 is at 0th index 2d_2 is at 1st index and 2d_3 is at 3rd index and it will be three day array since it is combination of 2d arrays


In [ ]:
# Multi-dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))  # it gives sum of all the elements

sum_of_columns = np.sum(arr2D,axis=0)  # use axis = 0 for performing operation on column
print(sum_of_columns)

sum_of_rows = np.sum(arr2D,axis = 1) # use axis = 1 for performing operation on rows
print(sum_of_rows)

#slicing ->lets print 2,5
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [31]:
#3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])    # 2 x 3 x 2
print(arr3D,arr3D.shape)

#indexing -> lets find 4
print(arr3D[0,1,1])

#lets access 9
print(arr3D[1,1,0])

#Slicing
# let access first row of both layers
print(arr3D[0:2,0:1,0:2])
# or 
print(arr3D[:,0,:])

# let we want first column of both layers
print(arr3D[:,:,0])


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[[1 2]]

 [[7 8]]]
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
#Vectorization -> dont need loop to do element wise operation like list

arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr+arr2)
print(arr**2)

[ 7  9 11 13 15]
[ 1  4  9 16 25]


In [ ]:
#Broadcasting -> any scalar let say 5 add to a vector then it will add to all elements of vector
# => it scales the array -> we have to perform mathematical operation on two values where there size incompatible it scale the scaler let say we have a array (1,2,3,4,5) and want to multiply each element by 2 the it will scale 2 as (2,2,2,2,2) and then each 2 is multiplied to each value of array respectively and it doesnt take any extra memory to scale(stretch)

arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr+5)
print(arr+arr2) # bradcast in two array happens if (x,y) and (p,q) y==q and  x or p should be 1 

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [ ]:
'''Vector Normalization -> one of the popular usecase of broadcasting
Normalizing an array means transforming its values so they fit into a specific scale or range  
let we have [[1,2],[3,4]] a 2d array and we want to scale ot between 0 to 1 means all element will be between 0 and 1 such that relative difference between each eelements will be maintain
normalizationn is used to increase performance  of ml algorithm 

std normalization = (arr-mean)/std deviation
std deviation = (((vali-mean)ka square ) esa sabka sum / number of values ) ka square root
'''
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)

normalized_arr = ((arr-mean)/std)
print(normalized_arr)
# if we do standard normalization like we have done then of normalized array mean = 0 and std deviation = 1

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


### Numpy Mathematical Function
1) Aggregation -> sum(), prod(), min(), max(), mean(), std(), var(), median(), argmin() -> returns index of where minimum value exist, argmax() -> return index of where maximum value exist.
2) Power -> square(), sqrt(), pow(a,b)
3) Log & Exponential -> log(), log10(), log2(), exp()
4) Rounding -> round(), floor(), ceil(), trunc()
5) EXTRAS -> unique(), sort(), abs()

In [11]:
#aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.median(arr))
print(np.argmin(arr)) # -> it returns the index of min value
print(np.argmax(arr)) # -> it returns the index of max value

15
120
1
5
3.0
1.4142135623730951
2.0
3.0
0
4


In [ ]:
#Power
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,arr))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[   1    4   27  256 3125]


In [14]:
#Log & Exponential
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [15]:
#Rounding
print(np.round(arr))
print(np.floor(arr))
print(np.ceil(arr))
print(np.trunc(arr))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [16]:
#EXTRAS
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
